name: C# .dot NET 8 -> Publicação automática

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar o .NET 8
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-8.0

      - name: Restaurar dependências
        run: dotnet restore

      - name: Compilar e publicar a aplicação
        run: dotnet publish -c Release -o ./publish

      - name: Criar um arquivo temporário para a chave privada
        run: |
          echo "${{ secrets.KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key

      - name: Criar a pasta da aplicação no servidor
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
          "sudo mkdir -p /home/ubuntu/appdotnet"

      - name: Ajustar permissões no servidor
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
          "sudo chown -R ubuntu:ubuntu /home/ubuntu/appdotnet && sudo chmod -R 755 /home/ubuntu/appdotnet"

      - name: Transferir os arquivos da aplicação para o servidor
        run: |
          scp -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./publish/* \
          ubuntu@${{ secrets.HOST }}:/home/ubuntu/appdotnet

      - name: Reiniciar o serviço da aplicação
        run: |
          ssh -i /tmp/private_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null ubuntu@${{ secrets.HOST }} \
          "sudo systemctl restart appdeploy.service"

      - name: Limpar o arquivo de chave privada após uso
        run: rm /tmp/private_key
